modules:
  robot:
    JointStatePerceptionModule: pepper_joints
  humans:
    OptitrackPerceptionModule: 
      - optitrack_1
      - optitrack_2
    StampedPosePerceptionModule: human
  objects:
    ArTrackPerceptionModule: ar_track
    StaticObjectsPerceptionModule: static

pepper_joints:
  robot_name : pepper

optitrack_1:
  name: human_1
  # offset_x: 6.4868
  offset_x: 6.5068
  offset_y: 2.9506
  # offset_y: 2.8506

optitrack_2:
  name: human_2
  # offset_x: 6.4868
  offset_x: 6.5068
  offset_y: 2.9506
  # offset_y: 2.8506

human:
  name: human_0

ar_track:
  min_track_err: 0.05

static:
  file: package://overworld/config/adream.yaml